version: '3.5'

services:

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    expose:
      - 9092
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: 'SSL://kafka:9092'
      KAFKA_LISTENERS: 'SSL://0.0.0.0:9092'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_SSL_KEYSTORE_LOCATION: '/tmp/ssl/kafka.server.keystore.jks'
      KAFKA_SSL_KEYSTORE_PASSWORD: 'serverpassword'
      KAFKA_SSL_KEY_PASSWORD: 'serverpassword'
      KAFKA_SSL_TRUSTSTORE_LOCATION: '/tmp/ssl/kafka.server.truststore.jks'
      KAFKA_SSL_TRUSTSTORE_PASSWORD: 'serverpassword'
      KAFKA_SSL_CLIENT_AUTH: 'required'
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: 'HTTPS'
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: 'SSL'
    volumes:
      - /tmp/ssl/:/tmp/ssl/

  kafka-rest-client:
    image: ftl/kafka-rest-client
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    volumes:
      - /tmp/ssl/:/tmp/ssl/

